/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#1e4288",
        "outline-variant": "#d8c1c5",
        "on-tertiary-fixed": "#1c1c17",
        "surface-tint": "#96435c",
        "on-background": "#001945",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#782c45",
        "tertiary": "#605e58",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "on-surface": "#001945",
        "inverse-on-surface": "#eef0ff",
        "inverse-primary": "#ffb1c4",
        "surface-container": "#e9edff",
        "on-secondary-fixed": "#001945",
        "on-secondary-fixed-variant": "#1f4489",
        "primary": "#96435c",
        "surface-variant": "#d9e2ff",
        "secondary-container": "#92b2ff",
        "secondary-fixed": "#d9e2ff",
        "on-surface-variant": "#534246",
        "surface-container-low": "#f2f3ff",
        "primary-container": "#f994af",
        "secondary": "#315399",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#d9e2ff",
        "on-primary-fixed": "#3f001a",
        "surface-bright": "#faf8ff",
        "primary-fixed-dim": "#ffb1c4",
        "outline": "#867276",
        "error": "#ba1a1a",
        "primary-fixed": "#ffd9e0",
        "inverse-surface": "#002d6e",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#e6e2da",
        "on-tertiary-fixed-variant": "#484741",
        "background": "#F4F0E8",
        "on-primary-container": "#752942",
        "tertiary-container": "#b5b2ab",
        "on-tertiary-container": "#46453f",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#b0c6ff",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#c9c6bf",
        "surface-container-high": "#e1e8ff",
        "surface-dim": "#cdd9ff",
        "surface": "#F4F0E8",
        "brand-alabaster": "#F4F0E8"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px"
      },
      spacing: {
        gutter: "24px",
        "container-max": "1280px",
        unit: "8px",
        "margin-mobile": "20px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "display-lg": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"]
      },
      fontSize: {
        "display-lg": ["80px", { lineHeight: "90px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "500" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
